Fix SQLite time column conversion to datetime object
Fixes:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/quasselgrep", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/quasselgrep/__main__.py", line 228, in main
    program = QuasselGrep()
              ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quasselgrep/__main__.py", line 58, in __init__
    for res in results: print(res)
  File "/usr/lib/python3.11/site-packages/quasselgrep/query.py", line 320, in formatter
    yield output.format(self.datetime_format, time, type, message, sender, buffer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/quasselgrep/output.py", line 10, in format
    formatted += '[%s] ' % time.strftime(datetime_format)
                           ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'strftime'

This error is still present when running with --debug, but that's
because EXPLAIN has a completely different return format and quasselgrep
never worked with it.